language: python
cache: pip
dist: trusty
python:
   - "2.7"
   - "3.5"
   - "3.6"
env:
   - PANDAS_VERSION=0.24.1
# Enable newer 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
    env: PANDAS_VERSION=0.24.1
before_install:
  - ls
install:
  - "pip install -r dev_requirements.txt"
  - "pip install pandas==$PANDAS_VERSION"
  - "pip freeze --local"
# command to run tests
script:
  - py.test --cov lifetimes
after_success:
  coveralls
# Don't want notifications
notifications:
  email: false
